#define MyAppName "Sistema Comercial"
#define MyAppURL "https://github.com/robertorp/EmissorCafe"
#define WizSmallImage "files\wl-wiz-small.bmp"
#define WizLeftImage "files\wl-wiz-left.bmp"
#define SetupIconFile "files\wl-setup.ico"